#!/usr/bin/env python3
"""Remodeling parameter sensitivity sweep (OFAT — one factor at a time).

Sweeps four key Huiskes remodeling parameters through plausible ranges while
holding the others at their baseline values from configs/remodeling.yaml.
For each parameter/value combination the script runs CYCLES_PER_VARIATION
full remodeling cycles (make_inp -> ccx -> extract_fields -> bone_remodeling)
then records density and stress/displacement metrics.

Output:
  results/parameter_sensitivity.csv
  results/sensitivity_dashboard.png  (generated by post/make_sensitivity_plots.py)

Usage:
  python3 scripts/parameter_sensitivity.py

Requires:
  ccx installed and in PATH
  mesh/mesh_data.json already generated
  configs/remodeling.yaml present
"""
from __future__ import annotations

import csv
import json
import os
import shutil
import subprocess
import sys
import time
from collections import OrderedDict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

# ---------------------------------------------------------------------------
# Sweep configuration
# ---------------------------------------------------------------------------
SWEEPS = OrderedDict([
    ("psi_ref_pa",       [1.0, 2.5, 5.0, 10.0, 25.0]),
    ("alpha_apposition", [0.0005, 0.001, 0.002, 0.004]),
    ("lazy_zone_s",      [0.0, 0.1, 0.2, 0.3]),
    ("n_power",          [1.5, 2.0, 2.5, 3.0]),
])
CYCLES_PER_VARIATION = 3
SCENARIO = "mewing"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REMODEL_CFG   = ROOT / "configs" / "remodeling.yaml"
SOLVER_DENS   = ROOT / "solver" / "elem_density.json"
RESULT_DENS   = ROOT / "results" / SCENARIO / "elem_density.json"
REMODEL_CSV   = ROOT / "results" / "remodeling_summary.csv"
SUTURE_MOD    = ROOT / "solver" / "suture_modulus.json"
OUT_CSV       = ROOT / "results" / "parameter_sensitivity.csv"

# Backup suffixes
BAK = ".paramsens_bak"


def _bak(p: Path) -> Path:
    return p.with_suffix(p.suffix + BAK)


def backup_files():
    """Backup all files that will be modified or deleted during the sweep."""
    for p in (REMODEL_CFG, SOLVER_DENS, RESULT_DENS, REMODEL_CSV, SUTURE_MOD):
        if p.exists():
            shutil.copy2(p, _bak(p))
            print(f"  [backup] {p.name}")


def restore_files():
    """Restore all backed-up files; remove originals that had no backup."""
    for p in (REMODEL_CFG, SOLVER_DENS, RESULT_DENS, REMODEL_CSV, SUTURE_MOD):
        bak = _bak(p)
        if bak.exists():
            shutil.copy2(bak, p)
            bak.unlink()
            print(f"  [restore] {p.name}")
        elif p.exists():
            # File was created during sweep but did not exist before
            os.remove(p)
            print(f"  [cleanup] removed {p.name} (did not exist before sweep)")


def remove_density_files():
    """Remove density state files so each variation starts from rho=1.0."""
    for p in (SOLVER_DENS, RESULT_DENS):
        if p.exists():
            os.remove(p)


def run_cmd(cmd: list[str], label: str, timeout: int = 300) -> None:
    """Run subprocess with check=True, streaming output."""
    print(f"    [{label}] {' '.join(cmd)}")
    t0 = time.time()
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout,
        cwd=str(ROOT),
    )
    elapsed = time.time() - t0
    if result.returncode != 0:
        print(f"    [{label}] FAILED (exit {result.returncode}, {elapsed:.1f}s)")
        if result.stderr:
            print(f"      stderr: {result.stderr[-400:]}")
        raise RuntimeError(f"{label} failed")
    print(f"    [{label}] OK ({elapsed:.1f}s)")


def read_baseline_defaults() -> dict:
    """Read current remodeling.yaml and return the remodeling sub-dict."""
    cfg = yaml.safe_load(REMODEL_CFG.read_text())
    return dict(cfg["remodeling"])


def patch_config(param: str, value: float) -> None:
    """Overwrite a single parameter in configs/remodeling.yaml."""
    cfg = yaml.safe_load(REMODEL_CFG.read_text())
    cfg["remodeling"][param] = value
    REMODEL_CFG.write_text(yaml.dump(cfg, default_flow_style=False))


def read_density_metrics(density_path: Path) -> dict:
    """Read elem_density.json and compute density statistics."""
    if not density_path.exists():
        return {"mean_rho": float("nan"), "min_rho": float("nan"),
                "max_rho": float("nan"), "rho_spread": float("nan")}
    data = json.loads(density_path.read_text())
    vals = list(data.values())
    if not vals:
        return {"mean_rho": float("nan"), "min_rho": float("nan"),
                "max_rho": float("nan"), "rho_spread": float("nan")}
    mean_rho = sum(vals) / len(vals)
    min_rho = min(vals)
    max_rho = max(vals)
    return {
        "mean_rho": mean_rho,
        "min_rho": min_rho,
        "max_rho": max_rho,
        "rho_spread": max_rho - min_rho,
    }


def read_remodeling_fractions() -> dict:
    """Read the last mewing row from remodeling_summary.csv for zone fractions."""
    defaults = {"apposition_frac": float("nan"),
                "resorption_frac": float("nan"),
                "lazy_frac": float("nan")}
    if not REMODEL_CSV.exists():
        return defaults
    last_row = None
    with REMODEL_CSV.open("r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("scenario") == SCENARIO:
                last_row = row
    if not last_row:
        return defaults
    return {
        "apposition_frac": float(last_row.get("apposition_fraction", "nan")),
        "resorption_frac": float(last_row.get("resorption_fraction", "nan")),
        "lazy_frac": float(last_row.get("lazy_fraction", "nan")),
    }


def read_peak_vm() -> float:
    """Read peak von Mises from elem_vm.csv."""
    csv_path = ROOT / "results" / SCENARIO / "elem_vm.csv"
    if not csv_path.exists():
        return float("nan")
    peak = 0.0
    with csv_path.open("r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                vm = float(row["vm_avg_pa"])
                if vm > peak:
                    peak = vm
            except (ValueError, KeyError):
                pass
    return peak


def read_max_displacement() -> float:
    """Read max displacement magnitude from node_u.csv."""
    csv_path = ROOT / "results" / SCENARIO / "node_u.csv"
    if not csv_path.exists():
        return float("nan")
    max_u = 0.0
    with csv_path.open("r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                u = float(row["u_mag"])
                if u > max_u:
                    max_u = u
            except (ValueError, KeyError):
                pass
    return max_u


def run_remodeling_cycles() -> None:
    """Run CYCLES_PER_VARIATION full remodeling cycles for the mewing scenario."""
    for cyc in range(1, CYCLES_PER_VARIATION + 1):
        run_cmd([sys.executable, "solver/make_inp.py"],
                f"make_inp c{cyc}", timeout=120)
        run_cmd(["./solver/run_case.sh", SCENARIO],
                f"ccx c{cyc}", timeout=300)
        run_cmd([sys.executable, "post/extract_fields.py"],
                f"extract c{cyc}", timeout=120)
        run_cmd([sys.executable, "post/bone_remodeling.py", SCENARIO, str(cyc)],
                f"remodel c{cyc}", timeout=120)
        # Feed density back to solver for next cycle
        if RESULT_DENS.exists():
            shutil.copy2(RESULT_DENS, SOLVER_DENS)


def main() -> None:
    if not shutil.which("ccx"):
        print("ERROR: ccx not found in PATH. Install CalculiX and retry.")
        sys.exit(1)

    defaults = read_baseline_defaults()
    print("=" * 70)
    print("  REMODELING PARAMETER SENSITIVITY SWEEP (OFAT)")
    print(f"  Scenario: {SCENARIO}  |  Cycles per variation: {CYCLES_PER_VARIATION}")
    print("=" * 70)
    print(f"\n  Baseline values from remodeling.yaml:")
    for param in SWEEPS:
        print(f"    {param:20s} = {defaults[param]}")
    print()

    (ROOT / "results").mkdir(parents=True, exist_ok=True)
    (ROOT / "results" / SCENARIO).mkdir(parents=True, exist_ok=True)

    backup_files()
    rows: list[dict] = []

    try:
        total = sum(len(v) for v in SWEEPS.values())
        count = 0

        for param, values in SWEEPS.items():
            print(f"\n{'='*60}")
            print(f"  PARAMETER: {param}  (baseline = {defaults[param]})")
            print(f"  Sweep values: {values}")
            print(f"{'='*60}")

            for val in values:
                count += 1
                print(f"\n  [{count}/{total}] {param} = {val}")

                # 1. Restore baseline config then patch the single parameter
                cfg_full = yaml.safe_load(_bak(REMODEL_CFG).read_text())
                cfg_full["remodeling"][param] = val
                REMODEL_CFG.write_text(yaml.dump(cfg_full, default_flow_style=False))

                # 2. Clean density state for fresh start
                remove_density_files()

                # 3. Remove stale remodeling_summary rows
                if REMODEL_CSV.exists():
                    os.remove(REMODEL_CSV)

                # 4. Run remodeling cycles
                try:
                    run_remodeling_cycles()
                except RuntimeError as e:
                    print(f"    SKIPPED ({e})")
                    continue

                # 5. Collect metrics
                dens = read_density_metrics(RESULT_DENS)
                fracs = read_remodeling_fractions()
                peak_vm = read_peak_vm()
                max_disp = read_max_displacement()

                row = {
                    "parameter": param,
                    "value": val,
                    "mean_rho": f"{dens['mean_rho']:.6f}",
                    "min_rho": f"{dens['min_rho']:.6f}",
                    "max_rho": f"{dens['max_rho']:.6f}",
                    "rho_spread": f"{dens['rho_spread']:.6f}",
                    "apposition_frac": f"{fracs['apposition_frac']:.6f}",
                    "resorption_frac": f"{fracs['resorption_frac']:.6f}",
                    "lazy_frac": f"{fracs['lazy_frac']:.6f}",
                    "peak_vm_pa": f"{peak_vm:.6e}",
                    "max_disp_m": f"{max_disp:.6e}",
                }
                rows.append(row)

                print(f"    mean_rho={dens['mean_rho']:.4f}  "
                      f"spread={dens['rho_spread']:.4f}  "
                      f"app={fracs['apposition_frac']:.1%}  "
                      f"lazy={fracs['lazy_frac']:.1%}  "
                      f"vm={peak_vm:.3e}  u={max_disp:.3e}")

    finally:
        print(f"\n{'='*60}")
        print("  Restoring original files...")
        restore_files()
        print(f"{'='*60}")

    # -----------------------------------------------------------------------
    # Write results CSV
    # -----------------------------------------------------------------------
    if rows:
        fieldnames = list(rows[0].keys())
        with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            w.writerows(rows)
        print(f"\nWrote {OUT_CSV}  ({len(rows)} rows)")

        # Print summary table
        print(f"\n{'parameter':20s} {'value':>8s} {'mean_rho':>9s} {'spread':>8s} "
              f"{'app%':>6s} {'lazy%':>6s} {'peak_vm':>11s} {'max_u':>11s}")
        print("-" * 90)
        for r in rows:
            print(f"{r['parameter']:20s} {float(r['value']):8.4f} "
                  f"{float(r['mean_rho']):9.4f} {float(r['rho_spread']):8.4f} "
                  f"{float(r['apposition_frac'])*100:5.1f}% "
                  f"{float(r['lazy_frac'])*100:5.1f}% "
                  f"{float(r['peak_vm_pa']):11.3e} {float(r['max_disp_m']):11.3e}")
    else:
        print("\nNo results collected. Check ccx and solver outputs.")
        sys.exit(1)

    # -----------------------------------------------------------------------
    # Generate dashboard plot
    # -----------------------------------------------------------------------
    print("\nGenerating sensitivity dashboard...")
    try:
        subprocess.run(
            [sys.executable, str(ROOT / "post" / "make_sensitivity_plots.py")],
            check=True,
            cwd=str(ROOT),
            timeout=60,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  Dashboard generation failed: {e}")
        print("  You can re-run manually: python3 post/make_sensitivity_plots.py")


if __name__ == "__main__":
    main()
